// Copyright 2026 Blink Labs Software
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package byron_test

import (
	_ "embed"
	"encoding/hex"
	"strings"
	"testing"

	"github.com/blinklabs-io/gouroboros/cbor"
	"github.com/blinklabs-io/gouroboros/ledger/byron"
	"github.com/blinklabs-io/gouroboros/ledger/common"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// The following four fixtures are cardano-ledger's own Byron golden CBOR
// test vectors, fetched directly from
// github.com/IntersectMBO/cardano-ledger,
// eras/byron/ledger/impl/golden/cbor/ssc/{CommitmentsMap,OpeningsMap,
// SharesMap,VssCertificatesMap} (master branch, retrieved 2026-08-07).
// Those files store an annotated hex dump (each line "<offset>:
// <hexbytes>"); the .hex files embedded here hold just the concatenated
// hex of the underlying CBOR bytes, decoded once and re-saved for a plain
// hex.DecodeString here. These are authoritative real-world (well, golden
// unit-test, generated by cardano-ledger's own Haskell encoders) examples
// of the exact wire shapes this file's shape-validation gate must accept:
// CommitmentsMap and VssCertificatesMap are each a genuine CBOR tag-258 set
// (confirmed below), OpeningsMap and SharesMap are each a genuine CBOR map
// keyed by a 28-byte ID (also confirmed below) -- see decodeIdentitySet's
// and decodeStakeholderMap's own doc comments in sscstate.go for why those
// are the two shapes cardano-ledger's dropCommitmentsMap/dropOpeningsMap/
// dropSharesMap decoders require.

//go:embed testdata/ssc-golden/CommitmentsMap.hex
var goldenCommitmentsMapHex string

//go:embed testdata/ssc-golden/OpeningsMap.hex
var goldenOpeningsMapHex string

//go:embed testdata/ssc-golden/SharesMap.hex
var goldenSharesMapHex string

//go:embed testdata/ssc-golden/VssCertificatesMap.hex
var goldenVssCertificatesMapHex string

// goldenSscBytes decodes one of the embedded golden-vector hex strings
// above into its raw CBOR bytes.
func goldenSscBytes(t *testing.T, hexStr string) []byte {
	t.Helper()
	raw, err := hex.DecodeString(strings.TrimSpace(hexStr))
	require.NoError(t, err)
	return raw
}

// TestByronSscGoldenVectorsHaveExpectedWireShape confirms, independently of
// this package's own decoders, exactly what wire shape each of
// cardano-ledger's four golden SSC vectors actually has -- so that the
// accept/reject assertions in the tests below are known to be exercising
// the real shapes cardano-ledger's own Haskell encoders produce, not some
// other incidental structure.
func TestByronSscGoldenVectorsHaveExpectedWireShape(t *testing.T) {
	// CommitmentsMap: a tag-258 set of ssccomm entries (each a 3-field
	// array: [pubkey, ..., signature]).
	var commsTag cbor.RawTag
	_, err := cbor.Decode(
		goldenSscBytes(t, goldenCommitmentsMapHex), &commsTag,
	)
	require.NoError(t, err)
	assert.Equal(t, uint64(cbor.CborTagSet), commsTag.Number)
	var commsItems []cbor.RawMessage
	_, err = cbor.Decode(commsTag.Content, &commsItems)
	require.NoError(t, err)
	assert.Len(t, commsItems, 1)

	// OpeningsMap: a genuine CBOR map keyed by a 28-byte stakeholder ID.
	var openings map[cbor.ByteString]cbor.RawMessage
	_, err = cbor.Decode(goldenSscBytes(t, goldenOpeningsMapHex), &openings)
	require.NoError(t, err)
	require.Len(t, openings, 1)
	for k := range openings {
		assert.Len(t, k.Bytes(), common.Blake2b224Size)
	}

	// SharesMap: a genuine CBOR map keyed by a 28-byte address ID.
	var shares map[cbor.ByteString]cbor.RawMessage
	_, err = cbor.Decode(goldenSscBytes(t, goldenSharesMapHex), &shares)
	require.NoError(t, err)
	require.Len(t, shares, 1)
	for k := range shares {
		assert.Len(t, k.Bytes(), common.Blake2b224Size)
	}

	// VssCertificatesMap: a tag-258 set of ssccert entries (each a 4-field
	// array: [vsspubkey, epochid, signature, pubkey]).
	var certsTag cbor.RawTag
	_, err = cbor.Decode(
		goldenSscBytes(t, goldenVssCertificatesMapHex), &certsTag,
	)
	require.NoError(t, err)
	assert.Equal(t, uint64(cbor.CborTagSet), certsTag.Number)
	var certsItems []cbor.RawMessage
	_, err = cbor.Decode(certsTag.Content, &certsItems)
	require.NoError(t, err)
	assert.Len(t, certsItems, 4)
}

// TestByronSscGoldenVectorsAcceptedByAccumulateBlock is the positive
// control: cardano-ledger's own golden CommitmentsMap, OpeningsMap,
// SharesMap, and VssCertificatesMap vectors, each embedded directly as the
// corresponding SSC payload field with no modification, must decode and
// accumulate successfully -- confirming this package's shape validation
// does not spuriously reject wire-correct data produced by cardano-ledger's
// own Haskell encoders.
func TestByronSscGoldenVectorsAcceptedByAccumulateBlock(t *testing.T) {
	comms := goldenSscBytes(t, goldenCommitmentsMapHex)
	openings := goldenSscBytes(t, goldenOpeningsMapHex)
	shares := goldenSscBytes(t, goldenSharesMapHex)
	certs := goldenSscBytes(t, goldenVssCertificatesMapHex)

	t.Run("CommitmentsMap", func(t *testing.T) {
		payload, err := cbor.Encode([]any{
			uint64(byron.SscTypeCommitments),
			cbor.RawMessage(comms),
			cbor.RawMessage(certs),
		})
		require.NoError(t, err)
		block := decodeWithSscPayload(t, payload)

		sscState := byron.NewByronEpochSscState()
		require.NoError(t, sscState.AccumulateBlock(block))
		assert.Len(t, sscState.Commitments, 1)
		assert.Len(t, sscState.VssCertificates, 4)
	})

	t.Run("OpeningsMap", func(t *testing.T) {
		payload, err := cbor.Encode([]any{
			uint64(byron.SscTypeOpenings),
			cbor.RawMessage(openings),
			cbor.RawMessage(certs),
		})
		require.NoError(t, err)
		block := decodeWithSscPayload(t, payload)

		sscState := byron.NewByronEpochSscState()
		require.NoError(t, sscState.AccumulateBlock(block))
		assert.Len(t, sscState.Openings, 1)
		assert.Len(t, sscState.VssCertificates, 4)
	})

	t.Run("SharesMap", func(t *testing.T) {
		payload, err := cbor.Encode([]any{
			uint64(byron.SscTypeShares),
			cbor.RawMessage(shares),
			cbor.RawMessage(certs),
		})
		require.NoError(t, err)
		block := decodeWithSscPayload(t, payload)

		sscState := byron.NewByronEpochSscState()
		require.NoError(t, sscState.AccumulateBlock(block))
		assert.Len(t, sscState.Shares, 1)
		assert.Len(t, sscState.VssCertificates, 4)
	})

	t.Run("VssCertificatesMap", func(t *testing.T) {
		payload, err := cbor.Encode([]any{
			uint64(byron.SscTypeCertificates),
			cbor.RawMessage(certs),
		})
		require.NoError(t, err)
		block := decodeWithSscPayload(t, payload)

		sscState := byron.NewByronEpochSscState()
		require.NoError(t, sscState.AccumulateBlock(block))
		assert.Len(t, sscState.VssCertificates, 4)
	})
}

// TestByronSscGoldenVectorsAcceptedByValidateBodyProof is the same positive
// control as TestByronSscGoldenVectorsAcceptedByAccumulateBlock, but
// through the actual proof-check entry point (ValidateBodyProof /
// checkSscProofLocal), which is the code path this fix (the shape gate
// before hashing rest[0]) touches. A real ssc_proof is computed directly
// from the golden bytes, exactly as checkSscProofLocal itself would.
func TestByronSscGoldenVectorsAcceptedByValidateBodyProof(t *testing.T) {
	comms := goldenSscBytes(t, goldenCommitmentsMapHex)
	certs := goldenSscBytes(t, goldenVssCertificatesMapHex)

	certState := byron.NewByronEpochSscState()
	certsOnlyPayload, err := cbor.Encode([]any{
		uint64(byron.SscTypeCertificates),
		cbor.RawMessage(certs),
	})
	require.NoError(t, err)
	require.NoError(
		t,
		certState.AccumulateBlock(decodeWithSscPayload(t, certsOnlyPayload)),
	)

	payload, err := cbor.Encode([]any{
		uint64(byron.SscTypeCommitments),
		cbor.RawMessage(comms),
		cbor.RawMessage(certs),
	})
	require.NoError(t, err)

	realProof, err := cbor.Encode([]any{
		uint64(byron.SscTypeCommitments),
		common.Blake2b256Hash(comms).Bytes(),
		certState.CertificatesHash().Bytes(),
	})
	require.NoError(t, err)

	blockCbor := withSscPayloadAndProof(
		t, mainnetByronBlock(t), payload, realProof,
	)
	block, err := byron.NewByronMainBlockFromCbor(blockCbor)
	require.NoError(t, err)

	assert.NoError(t, block.ValidateBodyProof())
}

// TestByronSscGoldenVectorsRejectMutatedShape is the negative control
// counterpart of TestByronSscGoldenVectorsAcceptedByAccumulateBlock: each
// golden vector is deliberately mutated to no longer have its required
// wire shape (an untagged array in place of the required tag-258 set for
// CommitmentsMap/VssCertificatesMap, or a plain array in place of the
// required real map for OpeningsMap/SharesMap, reusing that same golden
// vector's own decoded entry/entries as the mutated variant's content), and
// must be rejected -- both by AccumulateBlock and by ValidateBodyProof with
// a proof forged to genuinely match the mutated bytes' hash. This is the
// authoritative-fixture form of
// TestByronEpochSscStateRejectsUntaggedCommitmentsSet /
// TestByronEpochSscStateRejectsNonMapOpeningsField in sscstate_test.go.
func TestByronSscGoldenVectorsRejectMutatedShape(t *testing.T) {
	comms := goldenSscBytes(t, goldenCommitmentsMapHex)
	openings := goldenSscBytes(t, goldenOpeningsMapHex)
	shares := goldenSscBytes(t, goldenSharesMapHex)
	certs := goldenSscBytes(t, goldenVssCertificatesMapHex)

	// Strip the tag-258 wrapper from CommitmentsMap/VssCertificatesMap,
	// leaving the same entries as a plain, untagged array.
	untag := func(raw []byte) []byte {
		var tag cbor.RawTag
		_, err := cbor.Decode(raw, &tag)
		require.NoError(t, err)
		return []byte(tag.Content)
	}
	untaggedComms := untag(comms)
	untaggedCerts := untag(certs)

	// Re-wrap OpeningsMap/SharesMap's own single real entry value as a
	// plain array, instead of the required real CBOR map.
	toArray := func(raw []byte) []byte {
		var decoded map[cbor.ByteString]cbor.RawMessage
		_, err := cbor.Decode(raw, &decoded)
		require.NoError(t, err)
		values := make([]any, 0, len(decoded))
		for _, v := range decoded {
			values = append(values, v)
		}
		b, err := cbor.Encode(values)
		require.NoError(t, err)
		return b
	}
	arrayOpenings := toArray(openings)
	arrayShares := toArray(shares)

	cases := []struct {
		name    string
		sscType uint64
		primary []byte
	}{
		{"CommitmentsMap-untagged", byron.SscTypeCommitments, untaggedComms},
		{"OpeningsMap-as-array", byron.SscTypeOpenings, arrayOpenings},
		{"SharesMap-as-array", byron.SscTypeShares, arrayShares},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			payload, err := cbor.Encode([]any{
				tc.sscType,
				cbor.RawMessage(tc.primary),
				cbor.RawMessage(certs),
			})
			require.NoError(t, err)
			block := decodeWithSscPayload(t, payload)

			// AccumulateBlock rejects the mutated shape outright.
			sscState := byron.NewByronEpochSscState()
			err = sscState.AccumulateBlock(block)
			require.Error(t, err)
			assert.ErrorIs(t, err, byron.ErrBodyProofMismatch)

			// A real certificates hash, from a separate well-formed
			// CertificatesPayload sharing the same (unmutated) certs, so
			// that only the primary field's shape is under test.
			certState := byron.NewByronEpochSscState()
			certsOnlyPayload, err := cbor.Encode([]any{
				uint64(byron.SscTypeCertificates),
				cbor.RawMessage(certs),
			})
			require.NoError(t, err)
			require.NoError(t, certState.AccumulateBlock(
				decodeWithSscPayload(t, certsOnlyPayload),
			))

			// A proof forged to genuinely match blake2b256 of the mutated
			// primary field, exactly as checkSscProofLocal's primary-hash
			// check alone would compute -- isolating the new shape gate as
			// the only thing that can still reject this block.
			forgedProof, err := cbor.Encode([]any{
				tc.sscType,
				common.Blake2b256Hash(tc.primary).Bytes(),
				certState.CertificatesHash().Bytes(),
			})
			require.NoError(t, err)

			blockCbor := withSscPayloadAndProof(
				t, mainnetByronBlock(t), payload, forgedProof,
			)
			forgedBlock, err := byron.NewByronMainBlockFromCbor(
				blockCbor, common.VerifyConfig{SkipBodyHashValidation: true},
			)
			require.NoError(t, err)

			err = forgedBlock.ValidateBodyProof()
			require.Error(
				t, err,
				"ValidateBodyProof must reject a mutated-shape primary "+
					"field even when the header's ssc_proof hash "+
					"genuinely matches it",
			)
			assert.ErrorIs(t, err, byron.ErrBodyProofMismatch)
		})
	}

	// VssCertificatesMap's untagged mutation, exercised via
	// CertificatesPayload (the shape it is a single required field, rather
	// than the second of two, in).
	t.Run("VssCertificatesMap-untagged", func(t *testing.T) {
		payload, err := cbor.Encode([]any{
			uint64(byron.SscTypeCertificates),
			cbor.RawMessage(untaggedCerts),
		})
		require.NoError(t, err)
		block := decodeWithSscPayload(t, payload)

		sscState := byron.NewByronEpochSscState()
		err = sscState.AccumulateBlock(block)
		require.Error(t, err)
		assert.ErrorIs(t, err, byron.ErrBodyProofMismatch)

		// Unlike commitments/openings/shares, VSS certificates never hash
		// their preserved wire bytes directly: checkSscProofLocal's
		// certificates branch (localCertificatesHash) always hashes
		// canonicalMapHash of a *rebuilt*, stakeholder-keyed CBOR map
		// derived from each entry's own decoded pubkey field -- see
		// checkSscProofLocal's doc comment. A forged proof built from
		// blake2b256(untaggedCerts) directly (the raw-bytes hash) can
		// therefore never genuinely match what the code under test
		// computes, tag-258 or not, which would make this subtest's
		// ValidateBodyProof assertion pass on a hash mismatch alone,
		// telling us nothing about whether the untagged shape itself is
		// rejected.
		//
		// untaggedCerts has exactly the same entries as the well-formed,
		// tagged certs above, just without the outer tag-258 wrapper, and
		// canonicalMapHash's input never includes that wrapper -- only
		// each entry's own decoded stakeholder ID and preserved bytes. So
		// the hash a shape-check-free decode of untaggedCerts would
		// produce is identical to accumulating the well-formed certs
		// normally and reading its CertificatesHash back out, which is
		// what this does to genuinely forge that value without
		// depending on any shape check itself.
		certState := byron.NewByronEpochSscState()
		certsOnlyPayload, err := cbor.Encode([]any{
			uint64(byron.SscTypeCertificates),
			cbor.RawMessage(certs),
		})
		require.NoError(t, err)
		require.NoError(t, certState.AccumulateBlock(
			decodeWithSscPayload(t, certsOnlyPayload),
		))

		forgedProof, err := cbor.Encode([]any{
			uint64(byron.SscTypeCertificates),
			certState.CertificatesHash().Bytes(),
		})
		require.NoError(t, err)

		blockCbor := withSscPayloadAndProof(
			t, mainnetByronBlock(t), payload, forgedProof,
		)
		forgedBlock, err := byron.NewByronMainBlockFromCbor(
			blockCbor, common.VerifyConfig{SkipBodyHashValidation: true},
		)
		require.NoError(t, err)

		err = forgedBlock.ValidateBodyProof()
		require.Error(
			t, err,
			"ValidateBodyProof must reject an untagged VSS certificates "+
				"field even when the header's ssc_proof hash genuinely "+
				"matches what a shape-check-free decode would compute",
		)
		assert.ErrorIs(t, err, byron.ErrBodyProofMismatch)
	})
}
