#!/usr/bin/env python3

# This script reformats the CBOR visual representation generated by cbor.me so
# that it's actually readable

import sys

with open(sys.argv[1], 'r') as input_file:
    data = input_file.read()
    print('size = %d' % len(data))
    indent = 0
    in_string = False
    newline = False
    ignore_whitespace = False
    for idx, c in enumerate(data):
        if ignore_whitespace:
            if c == ' ':
                continue
            else:
                ignore_whitespace = False
        if in_string:
            if c == "'":
                in_string = False
        else:
            if c == '[':
                indent = indent + 2
                newline = True
            elif c == '{':
                indent = indent + 2
                newline = True
            elif c == ']':
                indent = indent - 2
            elif c == '}':
                indent = indent - 2
            elif c == ',':
                newline = True
            elif c == "'":
                in_string = True
        print(str(c), end='')
        if newline:
            newline = False
            ignore_whitespace = True
            print()
            print(' ' * indent, end='')
