name: pr
on:
  pull_request:

jobs:
  run-tests:
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: |
          make test

  build-test-program:
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: |
          make
